In [1]:
from mcda import DecisionMatrix

# Define geometries to compare
srad_parachute_design_options = [
    'Flat Ribbon',
    'Conical Ribbon',
    'Extended Skirt - 14.3%',
    'Ringsail',
    'DGB'
]

# Define selection variables
srad_parachute_variables = [
    'Average CD',
    'Opening Load Factor',
    'Inflated Shape (Dp/Do)',
    'Average Oscillation',
]

# Associate a percentage to each variable
srad_parachute_variables_percentages = [40, 30, 15, 15]
# Associate a unit to each variable
srad_parachute_units = ["[-]", "[-]", "[-]", "[°]"]
# Indicate if each variable must be maximized (True) or minimized (False)
srad_parachute_max_or_min_parameters = [True, False, True, False]

# Create selection matrix with the information above
srad_parachute_matrix = DecisionMatrix(
    srad_parachute_design_options,
    srad_parachute_variables,
    srad_parachute_units,
    srad_parachute_variables_percentages,
    srad_parachute_max_or_min_parameters
)

# Add performance information to each geometry (CD, Cx, Dp/Do & AoA)
srad_parachute_matrix.add_value_per_option('Flat Ribbon', [0.475, 1.321, 0.67, 1.5])
srad_parachute_matrix.add_value_per_option('Conical Ribbon', [0.525, 1.31, 0.7, 1.5])
srad_parachute_matrix.add_value_per_option('Extended Skirt - 14.3%', [0.825, 1.292, 0.68, 12.5])
srad_parachute_matrix.add_value_per_option('Ringsail', [0.825, 1.292, 0.69, 7.5])
srad_parachute_matrix.add_value_per_option('DGB', [0.55, 1.315, 0.65, 12.5])

d:\repos\utilities\general_utilities.py:2: SyntaxWarning: "is not" with 'str' literal. Did you mean "!="?
  if text is not "":

In [2]:
srad_parachute_matrix.get_matrix(True)

=================================================== ORIGINAL MATRIX ====================================================
+-----------------------------+------------+---------------------+------------------------+---------------------+
|                             | Average CD | Opening Load Factor | Inflated Shape (Dp/Do) | Average Oscillation |
+-----------------------------+------------+---------------------+------------------------+---------------------+
|         Flat Ribbon         |   0.475    |        1.321        |          0.67          |         1.5         |
|        Conical Ribbon       |   0.525    |         1.31        |          0.7           |         1.5         |
|    Extended Skirt - 14.3%   |   0.825    |        1.292        |          0.68          |         12.5        |
|           Ringsail          |   0.825    |        1.292        |          0.69          |         7.5         |
|             DGB             |    0.55    |        1.315        |          0.65          |         12.5        |
| Percentage per variable [%] |    40.0    |         30.0        |          15.0          |         15.0        |
+-----------------------------+------------+---------------------+------------------------+---------------------+
========================================================================================================================

,Average CD,Opening Load Factor,Inflated Shape (Dp/Do),Average Oscillation
Flat Ribbon,0.475,1.321,0.67,1.5
Conical Ribbon,0.525,1.310,0.70,1.5
Extended Skirt - 14.3%,0.825,1.292,0.68,12.5
Ringsail,0.825,1.292,0.69,7.5
DGB,0.550,1.315,0.65,12.5
Percentage per variable [%],40.000,30.000,15.00,15.0

In [4]:
srad_parachute_matrix.show_normalized_matrix()

================================================== NORMALIZED MATRIX ===================================================
========================================================================================================================

,Average CD,Opening Load Factor,Inflated Shape (Dp/Do),Average Oscillation
Flat Ribbon,0.575758,0.978047,0.957143,1.00
Conical Ribbon,0.636364,0.986260,1.000000,1.00
Extended Skirt - 14.3%,1.000000,1.000000,0.971429,0.12
Ringsail,1.000000,1.000000,0.985714,0.20
DGB,0.666667,0.982510,0.928571,0.12
Percentage per variable [%],40.000000,30.000000,15.000000,15.00

In [5]:
srad_parachute_matrix.best_option()

===================================================== FINAL SCORES =====================================================
Final score for Flat Ribbon: 81.73 points
Final score for Conical Ribbon: 85.04 points
Final score for Extended Skirt - 14.3%: 86.37 points
Final score for Ringsail: 87.79 points
Final score for DGB: 71.87 points
------------------------------------------------------------------------------------------------------------------------
                                 The best option is Ringsail with 87.79 points over 100
========================================================================================================================

(np.int64(3),
 array([81.72885391, 85.04233171, 86.37142857, 87.78571429, 71.87052327]))